//Given a string, WAM(write a method) to return all its subsequences in an arraylist A String is a subsequence of a
// given String that is generated by "deleting some character" of a given string "without changing order".
package Recursion;

import java.util.ArrayList;

public class returnSubsequences {
    static ArrayList<String> SSQ(String s){
        ArrayList<String> ans= new ArrayList<>();
        //base case
        if (s.length() == 0){  //ans er modheoo ekta empty string thaka uchit jkhn list er size 0 hbe
            ans.add(" ");
            return ans;
        }

        //recursion
        char curr= s.charAt(0);//a
        ArrayList<String> SmallAns = SSQ(s.substring(1));//bc
        //{bc, abc, b, ab, c, ac,  , a}
        for (String ss: SmallAns) {
            ans.add(ss); //bc
            ans.add(curr +ss); //abc
        }
        return ans;
    }
    public static void main(String[] args) {

        ArrayList<String> ans = SSQ("abcd");
        for (String ss: ans
             ) {
            System.out.println(ss);
        }
    }
}
//output
//
//a
//b 
//ab
//c
//ac
//bc
//abc
//d
//ad
//bd
//abd
//cd
//acd
//bcd
//abcd
